# Generated by Django 3.0.5 on 2020-04-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Escriu la categoria de l'esdeveniment.", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unic per aquest esdeveniment', primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('url', models.URLField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('category', models.ManyToManyField(help_text="Selecciona la categoria d'aquest esdeveniment.", to='meetups.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.Profile')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
