# Generated by Django 3.0.5 on 2020-04-20 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='end',
        ),
        migrations.AddField(
            model_name='meetup',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/media/profile_pics'),
        ),
    ]
