# Generated by Django 3.0.5 on 2020-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20200420_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
